#!/usr/bin/env bash

function append_to_file_if_not_there {
  # Grep doesn't like .* (and lots of other chars as well,
  # but we don't care about them yet)
  local escaped=$(echo "${1}" | sed "s/[*.]/\\\&/g")
  grep "${escaped}" "${2}" > /dev/null || echo "${1}" >> "${2}"
}

SCRIPT_DIR=$(dirname $(realpath $0))

echo "Set KONSO_SETTINGS_* env vars"
fish -c "set -Ux KONSO_SETTINGS_REPO ${SCRIPT_DIR}"
fish -c "set -Ux KONSO_SETTINGS_LAST_UPDATE $(date +\"%s\")"

echo "Install fish config file"
mkdir -p -v "${HOME}/.config/fish"
FISH_CONFIG="${HOME}/.config/fish/config.fish"
append_to_file_if_not_there "# Shared fish config" "${FISH_CONFIG}"
append_to_file_if_not_there ". ${SCRIPT_DIR}/config.fish" "${FISH_CONFIG}"

echo "Install/re-create nanorc"
NANORC_DIR="${HOME}/.config/nano"
NANORC="${NANORC_DIR}/nanorc"
mkdir -p -v "${NANORC_DIR}"
# nanorc is epheremeal - recreate every time
NANORC_TEMPLATE=$(cat << EOF
# THIS FILE IS AUTOMATICALLY GENERATED
# EVERY TIME SHARED SETTINGS ARE UPDATED
# CHANGES MANUALLY ADDED HERE *WILL* BE LOST
# Edit ${SCRIPT_DIR}/nanorc.edit-this
# if you want to sync your settings

# Syntax highlighting
include "${SCRIPT_DIR}/nano-syntax-highlighting/*.nanorc"
EOF
)
echo "${NANORC_TEMPLATE}" > "${SCRIPT_DIR}/nanorc"
cat "${SCRIPT_DIR}/nanorc.edit-this" >> "${SCRIPT_DIR}/nanorc"
if [[ -f "${NANORC}" ]] \
 && [[ $(readlink -f "${NANORC}") != "${SCRIPT_DIR}/nanorc" ]]
then
  echo "${NANORC} exists"
  mv -v --backup=numbered "${NANORC}" "${NANORC}.konso.bak"
fi
if [[ ! -f "${NANORC}" ]]; then
  echo "Create nanorc symlink"
  ln -sv "${SCRIPT_DIR}/nanorc" "${NANORC}"
fi

echo "Install ghostty config file"
GHOSTTY_CONFIG_DIR="${HOME}/.config/ghostty"
GHOSTTY_CONFIG_FILE="${GHOSTTY_CONFIG_DIR}/config"
mkdir -p "${GHOSTTY_CONFIG_DIR}"
if [[ ! -f "${GHOSTTY_CONFIG_FILE}" ]]; then
  echo "Config file ${GHOSTTY_CONFIG_FILE} doesn't exist, creating"
  touch "${GHOSTTY_CONFIG_FILE}"
fi
append_to_file_if_not_there "config-file = ${SCRIPT_DIR}/ghostty-config" "${GHOSTTY_CONFIG_FILE}"
append_to_file_if_not_there "gtk-custom-css = ${SCRIPT_DIR}/ghostty-toast-more-margin.css" "${GHOSTTY_CONFIG_FILE}"
