#!/usr/bin/env bash
echo "Calculating number of files and folders in ${1}..."
DU_RESULT=$(du -a "${1}" | wc -l)
echo "${DU_RESULT} entries found. Starting deletion."
rm -rfv "${1}" | pv -l -s "${DU_RESULT}" > /dev/null
